version: '3'

services:
  argus:
    build: .
    command: --host=influxdb populate --url ${URL} --days ${DAYS}
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.6
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
