
from argus.metrics.request_per_type import RequestPerType
import pytest
import tests.samples.loader as loader


class TestRequestPerType(object):
    @pytest.fixture
    def obj(self):
        obj = RequestPerType(loader.load_sample())
        return obj

    def test_measurement(self, obj):
        assert obj.measurement() == "request_per_type"

    def test_is_valid(self, obj):
        assert obj.is_valid() == True

    def test_fill(self, obj):
        assert obj.fill() == [
            {
                "fields": {"value": 8},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "html",
                    "id": "180904_HF_JMH",
                    "media_type": "text",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 4},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "css",
                    "id": "180904_HF_JMH",
                    "media_type": "text",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 13},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "javascript",
                    "id": "180904_HF_JMH",
                    "media_type": "application",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 5},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "font-woff2",
                    "id": "180904_HF_JMH",
                    "media_type": "application",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 21},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "javascript",
                    "id": "180904_HF_JMH",
                    "media_type": "text",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 53},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "webp",
                    "id": "180904_HF_JMH",
                    "media_type": "image",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 8},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "png",
                    "id": "180904_HF_JMH",
                    "media_type": "image",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 15},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "jpeg",
                    "id": "180904_HF_JMH",
                    "media_type": "image",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 22},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "gif",
                    "id": "180904_HF_JMH",
                    "media_type": "image",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 4},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "x-javascript",
                    "id": "180904_HF_JMH",
                    "media_type": "application",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 5},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "json",
                    "id": "180904_HF_JMH",
                    "media_type": "application",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 1},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "font-woff",
                    "id": "180904_HF_JMH",
                    "media_type": "application",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 2},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "plain",
                    "id": "180904_HF_JMH",
                    "media_type": "text",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
            {
                "fields": {"value": 1},
                "measurement": "request_per_type",
                "tags": {
                    "browser": "Chrome",
                    "city": "North America",
                    "connection": "Cable",
                    "country": "USA",
                    "device": "Machine",
                    "extension": "x-icon",
                    "id": "180904_HF_JMH",
                    "media_type": "image",
                    "region": "Dulles",
                    "website": "http://www.barenecessities.com",
                },
                "time": "2018-09-04T09:36:27Z",
            },
        ]
